name: cicd

on:
  workflow_dispatch:

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        run: echo "cloning the code"
  build:
    needs: [code]
    runs-on: ubuntu-latest
    steps:
      - name: Build using docker
        run: echo "Building the code"
  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Running the test cases
        run: echo "Testing the code"
  deploy:
    needs: [build,test]
    runs-on: ubuntu-latest
    steps:
      - name: Deploying on the machine
        run: echo "deploying the code"
